<a href="https://colab.research.google.com/github/naikdarshan45/python/blob/main/Mastering_the_Power_Of_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
arr = np.array([20, 40, 50, 60])
arr

array([20, 40, 50, 60])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# 2d array
arr2 = np.array([[20, 40],[50, 60]])
arr2

array([[20, 40],
       [50, 60]])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
#3d array
arr3 = np.array([[[20, 40],[50, 60]],[[3,4],[4,6]]])
arr3

array([[[20, 40],
        [50, 60]],

       [[ 3,  4],
        [ 4,  6]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape

(2, 2, 2)

In [ ]:
arr4 = np.array([[[20, 40],[50, 60]],[[3,4],[4,6]],[[3,8],[7,9]]])
arr4

array([[[20, 40],
        [50, 60]],

       [[ 3,  4],
        [ 4,  6]],

       [[ 3,  8],
        [ 7,  9]]])

In [ ]:
arr4.shape

(3, 2, 2)

In [ ]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [ ]:
np.linspace(1,9,6)

array([1. , 2.6, 4.2, 5.8, 7.4, 9. ])

In [ ]:
arr2

array([[20, 40],
       [50, 60]])

shallowArr = arr2

In [ ]:
deepArr = np.copy(arr2)

In [ ]:
arr2[0][0]=9
arr2

array([[ 9, 40],
       [50, 60]])

In [43]:
shallowArr

array([[ 9, 40],
       [50, 60]])

In [44]:
deepArr

array([[20, 40],
       [50, 60]])

In [45]:
np.fromfunction(lambda i,j: i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [46]:

np.fromfunction(lambda i,j: i+j, (4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [47]:
np.fromfunction(lambda i,j: i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [48]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
dataset = np.linspace(2,9, 50)

In [51]:
dataset

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
       3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
       4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
       4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143,
       5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
       6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
       7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
       7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
       8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ])

In [52]:
dataset.shape

(50,)

In [56]:
dataset.reshape(2,1,25)

array([[[2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
         2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
         3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
         4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
         4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143]],

       [[5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
         6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
         7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
         7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
         8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ]]])